### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by julio641742** [freeekanayaka/libco#2]
Hello there, I am trying to package [dqlite](https://github.com/CanonicalLtd/dqlite) which requires libco.
dqlite developers [import](https://code.launchpad.net/~dqlite-maintainers/dqlite/+git/libco) this repo so they can package it for debian/ubuntu.
I want to package this library for Voidlinux but they do not accept any packages containing non-release versions such as specific git-revisions anymore. Could you tag a release so I and other distributions can package it? Thanks.

**Comment by freeekanayaka** [comment]
Done, see the [releases](https://github.com/freeekanayaka/libco/releases) page.

**Comment by julio641742** [comment]
Thanks
